Improved handling of w_dir = None
The plugin crashed sometimes due to an addition of a float and w_dir = None values:
Traceback (most recent call last):
  File "/usr/share/weewx/user/rtcr.py", line 768, in run
    self.process_packet(_package['payload'])
  File "/usr/share/weewx/user/rtcr.py", line 808, in process_packet
    self.buffer.add_packet(packet_wx)
  File "/usr/share/weewx/user/rtcr.py", line 2208, in add_packet
    obs in HIST_MANIFEST, obs in SUM_MANIFEST)
  File "/usr/share/weewx/user/rtcr.py", line 2237, in add_wind_value
    packet['dateTime'], False, True, False)
  File "/usr/share/weewx/user/rtcr.py", line 1874, in _add_value
    math.cos(math.radians(90.0 - w_dir)),
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'